module.exports = {
    init:{
        Id:1,
        json:JSON.stringify({
          user:"22",
          psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
          Escuela:"0",
          Tipo:"App",
          Tabla:"ProgramInquiry",
          Rows:[{
            action:"I",
            Data:"0|PLOTE|A|F|@0|"
          }]
        }),
        Category:"Mi App"
    },
    labels:{
        Id:1,
        json:JSON.stringify({
          user:"22",
          psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
          Escuela:"0",
          Tipo:"App",
          Tabla:"ProgramInquiry",
          Rows:[{
            action:"I",
            Data:"0|PLOTE|E|B|@0@@@@@20240430@@|"
          }]
        }),
        Category:"Mi App"
    },
    list_data:{
      Id:1,
      json:JSON.stringify({
        user:"22",
        psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
        Escuela:"0",
        Tipo:"App",
        Tabla:"ProgramInquiry",
        Rows:[{
          action:"I",
          Data:"0|PLOTE|F|B|@0@@@@@20240430@@|"
        }]
      }),
      Category:"Mi App"
  },
  buttons:{
    Id:1,
    json:JSON.stringify({
      user:"22",
      psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
      Escuela:"0",
      Tipo:"App",
      Tabla:"INQBARRA",
      Rows:[{
        action:"I",
        Data:"0|1|"
      }]
    }),
    Category:"Mi App"
  },
  buttons_footer:{
    Id:1,
    json:JSON.stringify({
      user:"22",
      psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
      Escuela:"0",
      Tipo:"App",
      Tabla:"BARRAPROGRAM",
      Rows:[{
        action:"I",
        Data:"0|PLOTE|"
      }]
    }),
    Category:"Mi App"
  }
}