module.exports = {
    init:{
        Id:1,
        json:JSON.stringify({
          user:"22",
          psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
          Escuela:"0",
          Tipo:"App",
          Tabla:"ProgramInquiry",
          Rows:[{
            action:"I",
            Data:"0|PLOTE|A|F|@0|"
          }]
        }),
        Category:"Mi App"
    },
    btn_buscar:{
      Id:1,
      json:JSON.stringify({
        user:"22",
        psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
        Escuela:"0",
        Tipo:"App",
        Tabla:"ProgramInquiry",
        Rows:[{
          action:"I",
          Data:"0|PLOTE|I|B||"
        }]
      }),
      Category:"Mi App"
  },
    labels:{
        Id:1,
        json:JSON.stringify({
          user:"22",
          psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
          Escuela:"0",
          Tipo:"App",
          Tabla:"ProgramInquiry",
          Rows:[{
            action:"I",
            Data:"0|PLOTE|E|B|@0@@@@@20240430@@|"
          }]
        }),
        Category:"Mi App"
    },
    list_data:{
      Id:1,
      json:JSON.stringify({
        user:"22",
        psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
        Escuela:"0",
        Tipo:"App",
        Tabla:"ProgramInquiry",
        Rows:[{
          action:"I",
          Data:"0|PLOTE|F|B|@0@@@@@20240430@@|"
        }]
      }),
      Category:"Mi App"
  },
  buttons:{
    Id:1,
    json:JSON.stringify({
      user:"22",
      psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
      Escuela:"0",
      Tipo:"App",
      Tabla:"INQBARRA",
      Rows:[{
        action:"I",
        Data:"0|1|"
      }]
    }),
    Category:"Mi App"
  },
  buttons_footer:{
    Id:1,
    json:JSON.stringify({
      user:"22",
      psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
      Escuela:"0",
      Tipo:"App",
      Tabla:"BARRAPROGRAM",
      Rows:[{
        action:"I",
        Data:"0|PLOTE|"
      }]
    }),
    Category:"Mi App"
  },
  buttons_header_form:{
    Id:1,
    json:JSON.stringify({
      user:"22",
      psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
      Escuela:"0",
      Tipo:"App",
      Tabla:"INQBARRAFIX",
      Rows:[{
        action:"I",
        Data:"0|1|"
      }]
    }),
    Category:"Mi App"
  },
  get_data:{
    Id:1,
    json:JSON.stringify({
      user:"22",
      psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
      Escuela:"0",
      Tipo:"App",
      Tabla:"ProgramInquiry",
      Rows:[{
        action:"I",
        Data:""
      }]
    }),
    Category:"Mi App"
  },
  categoria1:{
    Id:1,
    json:JSON.stringify({
      user:"22",
      psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
      Escuela:"0",
      Tipo:"App",
      Tabla:"PGMINQUIRY",
      Rows:[{
        action:"I",
        Data:"0|FYEAR_AEYEAR|1|"
      }]
    }),
    Category:"Mi App"
  },
  categoria2:{
    Id:1,
    json:JSON.stringify({
      user:"22",
      psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
      Escuela:"0",
      Tipo:"App",
      Tabla:"PGMINQUIRY",
      Rows:[{
        action:"I",
        Data:"0|GRUPO|1|"
      }]
    }),
    Category:"Mi App"
  },
  guardar:{
    Id:1,
    json:JSON.stringify({
      Function:'ValidateInfo',
      Program:'FLOTE',
      user:"22",
      psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
      ID:"0",
      Parameter:""
    }),
    Category:"Utilerias"
  },
  buscar: {
    Id:1,
    json:JSON.stringify({
      user:"22",
      psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
      Escuela:"0",
      Tipo:"App",
      Tabla:"ProgramInquiry",
      Rows:[{
        action:"I",
        Data:""
      }]
    }),
    Category:"Mi App"
  },
  delete: {
    Id:1,
    json:JSON.stringify({
      user:"22",
      psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
      Escuela:"0",
      Tipo:"App",
      Tabla:"PLOTE",
      Rows:[{
        action:"D",
        Data:""
      }]
    }),
    Category:"Mi App"
  },
  inputs_preport:{
    Id:1,
    json:JSON.stringify({
      user:"22",
      psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
      Escuela:"0",
      Tipo:"App",
      Tabla:"ProgramInquiry",
      Rows:[{
        action:"I",
        Data:"0|PREPORTS|I|B||"
      }]
    }),
    Category:"Mi App"
  },
  btn_preport_header:{
    Id:1,
    json:JSON.stringify({
      user:"22",
      psw:"JrVZl/C6Gr/dLBQMKJXJVA==",
      Escuela:"0",
      Tipo:"App",
      Tabla:"BARRAPROGRAM",
      Rows:[{
        action:"I",
        Data:"0|PREPORTS|"
      }]
    }),
    Category:"Mi App"
  }
}